# Site settings
title:          YaoFly in action
description:    "Rain is a simple and clean Jekyll theme with focus on content."
url:            https://yaofly.github.io/

# Author
author:
  name:         YaoFly
  email:        2465939235@qq.com
#  url:          https://inelaah.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: 2465939235@qq.com
  github: https://github.com/YaoFly
#  twitter: https://twitter.com
#  linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
